# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e42429323696c8bb871db21233c227cf903d369d03026a5b1f697ca3ed932bd794e7e79f695fdee706cd4d689d65035df636ae317248838bd013fefa157f0c5
  GOOGLE_CLIENT_ID: 867315174604-o9vkf5lo034daqj8h8vtrehq2ifkgt04.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: 0ygGlRpfnpMQEPOZw3zmlGDY
  TWITTER_API_KEY: HDYtAcMGrzLtsv5Bv2U0pEUl1
  TWITTER_SECRET_KEY: yAO7xua7G619HhbhZCQP9oSmYyquuSoZlFWag6iwQyomtFdB07
  TWITTER_ACCESS_TOKEN: 1601755230-XzBP1GCpqqZVugjfjEY4848FEO0Nxhlo1JUP8E5
  TWITTER_ACCESS_TOKEN_SECRET: lUZe8aUJaSmOEoUFDIGRLtVyoJSMt3XwCFq4SniMYJ4nn

test:
  secret_key_base: 94d1cb8375d4b620de0d2b18306c75739e9a6ab3a2742a07b12ef9eb7069d1fb3d9cfb7fd8fdfcfac575ea0bb022838b23681fb48443c6c24b69594602b1bc31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
